ALTER TABLE `xwlb_text` ALGORITHM = INPLACE,
CHANGE COLUMN  `TITLE`    `TITLE`     VARCHAR(1024) NOT NULL COMMENT '标题',
CHANGE COLUMN  `DATE`     `DATE`      BIGINT(20) NOT NULL COMMENT '日期',
CHANGE COLUMN  `SUMMARY`  `SUMMARY`   TEXT COMMENT '摘要',
CHANGE COLUMN  `CONTENT`  `CONTENT`   TEXT COMMENT '内容',
CHANGE COLUMN  `URL`      `URL`       VARCHAR(256) COMMENT '原文链接';
ALTER TABLE `xwlb_text` COMMENT '文字内容表';


ALTER TABLE `xwlb_word` ALGORITHM = INPLACE,
CHANGE COLUMN  `WORD`       `WORD`       VARCHAR(128) NOT NULL COMMENT '关键字',
CHANGE COLUMN  `TEXT_IDS`   `TEXT_IDS`   TEXT COMMENT '内容索引列表';
ALTER TABLE `xwlb_word` COMMENT '关键字表';