server:
  port: 8088
spring:
  application:
    name: xwlb-scheduler

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka